name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        lfs: true

    - name: Trigger deployment on EasyPanel
      run: |
        curl -X POST http://82.180.163.169:3000/api/deploy/30a4729af594dbd55c920abcc9044fa7884321d7650c9367
