name: Deploy

on:
  push:
    branches:
      - main  # Change to your deployment branch if different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        lfs: true  # This ensures LFS files are pulled when checking out

    - name: Set up Git LFS
      run: |
        git lfs install
        git lfs pull

    - name: Deploy application
      run: |
        # Here you can run your deployment script or any necessary commands
        # For example, you might SSH into your server and pull the latest changes
        ssh user@yourserver "cd /path/to/your/project && git pull && git lfs pull && ./deploy_script.sh"
